=== cyristo/apifit/src/test/resources/Good_Schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"hotels": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"conditions": {
			"type": "object",
			"properties": {
				"context": {
					"type": "string"
				},
				"packagedMainProductToFilter": {
					"type": "array",
					"items": {
						"type": "string"
					},
					"optional": true
				}
			},
			"required": [
				"context"
			]
		},
		"unqualifiedPolicy": {
			"type": "string"
		},
		"segmentCriterias": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"dateIn": {
						"type": "string"
					},
					"los": {
						"type": "integer"
					},
					"nbRooms": {
						"type": "integer"
					},
					"paxCriteria": {
						"type": "object",
						"properties": {
							"pax": {
								"type": "integer"
							},
							"nbChildrens": {
								"type": "integer"
							},
							"childrenAges": {
								"type": "array",
								"items": {}
							}
						},
						"required": [
							"pax",
							"nbChildrens",
							"childrenAges"
						]
					}
				},
				"required": [
					"dateIn",
					"los",
					"nbRooms",
					"paxCriteria"
				]
			}
		},
		"mainCroSubCroPK": {
			"type": "object",
			"properties": {
				"mainCro": {
					"type": "string"
				},
				"subCro": {
					"type": "string"
				}
			},
			"required": [
				"mainCro",
				"subCro"
			]
		}
	},
	"required": [
		"hotels",
		"conditions",
		"unqualifiedPolicy",
		"segmentCriterias",
		"mainCroSubCroPK"
	]
}

=== cyristo/apifit/src/test/resources/Good_Example.json
{
    "hotels": ["6752", "6722", "0716", "5282"],
    "conditions": {
        "context": "MULTI_HOTELS",
        "packagedMainProductToFilter": ["ESCALV", "ESCALB"]
    },
    "unqualifiedPolicy": "QUALIFIED_AND_UNQUALIFIED",
    "segmentCriterias": [{
        "dateIn": "2017-01-25",
        "los": 2,
        "nbRooms": 1,
        "paxCriteria": {
            "pax": 2,
            "nbChildrens": 0,
            "childrenAges": []
        }
    }],
    "mainCroSubCroPK": {
        "mainCro": "INT",
        "subCro": "WTC"
    }
}
